name: Create new release

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    #runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: Get appimagetool
      run: |
        set -x
        #wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"

        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        pwd; ls -lah

    - name: Get Pyhton AppImage
      run: |
        set -x
        # Ok
        #wget -q https://github.com/niess/python-appimage/releases/download/python3.10/python3.10.6-cp310-cp310-manylinux2010_x86_64.AppImage
        wget -q https://github.com/ryuuzaki42/Python_to_make_AppImage/releases/download/06/python3.13.3-cp313-cp313-manylinux2014_x86_64.AppImage

        ## Error
        #wget -q https://github.com/niess/python-appimage/releases/download/python3.14/python3.14.0-cp314-cp314t-manylinux_2_28_x86_64.AppImage

        fileName=$(ls python3*.AppImage)
        chmod +x "$fileName"
        ./"$fileName" --appimage-extract
        pwd; ls -lah

    - name: Install MComix and update pip
      run: |
        set -x
        version=$(grep -o "MComix:.*" README.md | cut -d ' ' -f2)
        echo "MComix version: $version"

        cd squashfs-root/opt/python3*/bin/
        pwd; ls -lah

        # meson.build: ERROR 'gobject-introspection-1.0' not found
        sudo apt install libgirepository1.0-dev

        #./pip3.* install PyGObject
        ./pip3.* install PyGObject==3.50.0

        #./pip3.* install pycairo

        # https://sourceforge.net/projects/mcomix/files/
        # https://sourceforge.net/p/mcomix/wiki/Installation/
        #version="3.1.1" # Built locally
        wget -q https://sourceforge.net/projects/mcomix/files/MComix-$version/mcomix-$version.tar.gz

        tar -xvf mcomix-$version.tar.gz
        rm mcomix-$version.tar.gz
        cd mcomix-$version/
        ../python3.* -m pip install .

        pwd; ls -lah
        cd ../
        ./python3.* -m pip install --upgrade pip

    - name: Make AppImage
      run: |
        set -x
        version=$(grep -o "MComix:.*" README.md | cut -d ' ' -f2)
        echo "MComix version: $version"
        tag=2 #1

        cd squashfs-root/
        rm -v .DirIcon AppRun
        pwd; ls -lah

        #find . | grep ".png"
        rm python.png
        ln -s opt/python3.*/bin/mcomix-$version/share/icons/hicolor/48x48/apps/mcomix.png .
        pwd; ls -lah

        #find . | grep ".desktop"
        rm python*.desktop
        ln -s opt/python3.*/bin/mcomix-$version/share/applications/mcomix.desktop MComix.desktop
        cat MComix.desktop

        echo '#!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"
        echo -e "Running MComix with parameter: \"$1\"\n"
        if [ "$1" != "" ]; then
            par_1="$PWD/$1" # Add the current directory, $PWD, to the first parameter
            "$HERE"/opt/python3.*/bin/python3.* "$HERE"/opt/python3.*/bin/mcomix "$par_1"
        else
            "$HERE"/opt/python3.*/bin/python3.* "$HERE"/opt/python3.*/bin/mcomix
        fi' > AppRun
        chmod +x AppRun
        cat AppRun

        cd ../
        cp README.md squashfs-root/
        ls -lah squashfs-root/

        # Wrong permissions on AppDir, please set it to 0755 and try again
        chmod 0755 squashfs-root/

        #ARCH=x86_64 ./appimagetool-x86_64.AppImage squashfs-root/
        ARCH=x86_64 VERSION="${version}-${tag}_JB" ./appimagetool-x86_64.AppImage squashfs-root/
        pwd; ls -lah

        fileName=$(ls MComix*.AppImage)
        echo "fileName: $fileName"
        md5sum "$fileName" > "${fileName}.md5"
        pwd; ls -lah

    - uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "MComix*.AppImage; MComix*.zsync; MComix*.md5"
          #overwrite: true
          verbose: true
          draft: false
          default_release_name: "MComix V in AppImage"
